spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easybuy
  jpa:
      show-sql: true
  jackson:
    default-property-inclusion: non_null